package scmapanalyzer

// hdSpriteUnitNames maps Brood War unit type id to display name for each embedded
// HD sprite (file hd_units/u<ID>.qoi). Names are stable labels for [UnitOrBuildingImagePNG];
// duplicate display names resolve to the lowest unit id.
var hdSpriteUnitNames = map[uint16]string{
	0:   "Terran Marine",
	1:   "Terran Ghost",
	2:   "Terran Vulture",
	3:   "Terran Goliath",
	5:   "Terran Siege Tank",
	7:   "Terran SCV",
	8:   "Terran Wraith",
	9:   "Terran Science Vessel",
	11:  "Terran Dropship",
	12:  "Terran Battlecruiser",
	30:  "Terran Siege Tank",
	32:  "Terran Firebat",
	34:  "Terran Medic",
	37:  "Zerg Zergling",
	38:  "Zerg Hydralisk",
	39:  "Zerg Ultralisk",
	40:  "Zerg Broodling",
	41:  "Zerg Drone",
	42:  "Zerg Overlord",
	43:  "Zerg Mutalisk",
	44:  "Zerg Guardian",
	45:  "Zerg Queen",
	46:  "Zerg Defiler",
	47:  "Zerg Scourge",
	50:  "Infested Terran",
	58:  "Terran Valkyrie",
	60:  "Protoss Corsair",
	61:  "Protoss Dark Templar",
	62:  "Zerg Devourer",
	63:  "Protoss Dark Archon",
	64:  "Protoss Probe",
	65:  "Protoss Zealot",
	66:  "Protoss Dragoon",
	67:  "Protoss High Templar",
	68:  "Protoss Archon",
	69:  "Protoss Shuttle",
	70:  "Protoss Scout",
	71:  "Protoss Arbiter",
	72:  "Protoss Carrier",
	73:  "Protoss Interceptor",
	83:  "Protoss Reaver",
	84:  "Protoss Observer",
	85:  "Protoss Scarab",
	103: "Zerg Lurker",
	106: "Terran Command Center",
	107: "Terran Comsat Station",
	108: "Terran Nuclear Silo",
	109: "Terran Supply Depot",
	110: "Terran Refinery",
	111: "Terran Barracks",
	112: "Terran Academy",
	113: "Terran Factory",
	114: "Terran Starport",
	115: "Terran Control Tower",
	116: "Terran Science Facility",
	117: "Terran Covert Ops",
	118: "Terran Physics Lab",
	120: "Terran Machine Shop",
	122: "Terran Engineering Bay",
	123: "Terran Armory",
	124: "Terran Missile Turret",
	125: "Terran Bunker",
	130: "Infested Command Center",
	131: "Zerg Hatchery",
	132: "Zerg Lair",
	133: "Zerg Hive",
	134: "Zerg Nydus Canal",
	135: "Zerg Hydralisk Den",
	136: "Zerg Defiler Mound",
	137: "Zerg Greater Spire",
	138: "Zerg Queen's Nest",
	139: "Zerg Evolution Chamber",
	140: "Zerg Ultralisk Cavern",
	141: "Zerg Spire",
	142: "Zerg Spawning Pool",
	143: "Zerg Creep Colony",
	144: "Zerg Spore Colony",
	146: "Zerg Sunken Colony",
	149: "Zerg Extractor",
	154: "Protoss Nexus",
	155: "Protoss Robotics Facility",
	156: "Protoss Pylon",
	157: "Protoss Assimilator",
	159: "Protoss Observatory",
	160: "Protoss Gateway",
	162: "Protoss Photon Cannon",
	163: "Protoss Citadel of Adun",
	164: "Protoss Cybernetics Core",
	165: "Protoss Templar Archives",
	166: "Protoss Forge",
	167: "Protoss Stargate",
	169: "Protoss Fleet Beacon",
	170: "Protoss Arbiter Tribunal",
	171: "Protoss Robotics Support Bay",
	172: "Protoss Shield Battery",
}
